// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for consultor documents
 */
interface ConsultorDocumentData {
  /**
   * Representante Imagem field in *consultor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: consultor.representante_imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  representante_imagem: prismic.ImageField<never>;

  /**
   * Representante Nome field in *consultor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultor.representante_nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  representante_nome: prismic.KeyTextField;

  /**
   * Representante Número field in *consultor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultor.representante_numero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  representante_numero: prismic.KeyTextField;
}

/**
 * consultor document from Prismic
 *
 * - **API ID**: `consultor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConsultorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ConsultorDocumentData>,
    "consultor",
    Lang
  >;

export type AllDocumentTypes = ConsultorDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type { ConsultorDocument, ConsultorDocumentData, AllDocumentTypes };
  }
}
